[project]
name = "prediction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "livnxin", email = "lilixinxin@protonmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[project.scripts]
prediction = "prediction:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
