apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: prediction
  namespace: application
spec:
  interval: 5m0s
  chart: ./chart/prediction
  sourceRef:
    kind: GitRepository
    name: flux-system
  reconcileStrategy: Revision

---

apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prediction
  namespace: application
spec:
  chartRef:
    kind: HelmChart
    name: podinfo
    namespace: application
  interval: 5m0s
